name: Lint

on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install
        run: npm ci
      
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

  eslint:
    runs-on: ubuntu-latest
    needs: [ install ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      
      - name: Install
        if: ${{ !steps.cache.outputs.cache-hit }}
        run: npm ci

      - run: npm run lint:js

  stylelint:
    runs-on: ubuntu-latest
    needs: [ install ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      
      - name: Install
        if: ${{ !steps.cache.outputs.cache-hit }}
        run: npm ci

      - run: npm run lint:css
  
  prettier:
    runs-on: ubuntu-latest
    needs: [ install ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      
      - name: Install
        if: ${{ !steps.cache.outputs.cache-hit }}
        run: npm ci

      - run: npm run lint:format

  type-check:
    runs-on: ubuntu-latest
    needs: [ install ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      
      - name: Install
        if: ${{ !steps.cache.outputs.cache-hit }}
        run: npm ci

      - run: npm run type-check
